### ISSUE TITLE
Nimbus - Failed to fetch peers

### ISSUE THREAD

**Issue by eangus262** [ethpandaops/ethereum-metrics-exporter#52]
Following error is repeating in the logs:

Nov 19 18:00:54 Ubuntu-VM ethereum-metrics-exporter[21296]: {"component":"exporter","error":"nats: maximum payload exceeded","level":"error","module":"consensus/beacon","msg":"Failed to fetch peers","time":"2022-11-19T18:00:54-07:00"}

All other metrics seem to  pull in just fine, both for execution and remaining consensus metrics. Also, able to get peers from Nimbus using the metrics exported by Nimbus itself with no problem.

Attached logfile of the startup of ethereum-metrics-exporter.
Nimbus v. 22.10.1
Besu v. 22.10.0
go v. 1.19.3
prometheus v. 2.39.1

[ethereum-metrics-exporter.log](https://github.com/ethpandaops/ethereum-metrics-exporter/files/10048264/ethereum-metrics-exporter.log)

**Comment by samcm** [comment]
Should be fixed with: https://github.com/ethpandaops/ethereum-metrics-exporter/pull/53 & https://github.com/ethpandaops/ethereum-metrics-exporter/pull/54, thanks for the issue!
