### ISSUE TITLE
linux/arm64 docker image not compatible

### ISSUE THREAD

**Issue by mdominoni** [ethpandaops/ethereum-metrics-exporter#62]
ethereum-metrics-exporter The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by nikwest** [comment]
the image in the repository seems to be only for linux/amd64 platforms. I built it myself for linux/arm64. But would be nice to have a multiplatform image in the repository. You can find my version at nikwest/ethereum-metrics-exporter, if you don't want to build it yourself.

**Comment by yorickdowne** [comment]
+1. A multiarch amd64/arm64 image would be most excellent, and useful for deploying on Rock5 B/Proteus (or even Pi4) as well as Mac M1/M2.

**Comment by samcm** [comment]
Can do 👍

**Comment by yorickdowne** [comment]
🎉

**Comment by samcm** [comment]
Available as a part of `v0.20.0` 😄 

https://github.com/ethpandaops/ethereum-metrics-exporter/releases/tag/v0.20.0
