### ISSUE TITLE
Ethereum Metrics Exporter Listening on Port 4222?

### ISSUE THREAD

**Issue by metanull-operator** [ethpandaops/ethereum-metrics-exporter#79]
I see this in my `sudo netstat -tnlp` output:

`tcp6       0      0 :::4222                 :::*                    LISTEN      755/ethereum-metric`

I have not yet found a reference to this port in the code or docs. 

I am running Ethereum Metrics Exporter with `--metrics-port 9095` and it is responding to requests on that port correctly.

What is port 4222 being used for?

**Comment by samcm** [comment]
What version are you running @metanull-operator?

**Comment by samcm** [comment]
I believe this will be NATS, which we removed in https://github.com/ethpandaops/ethereum-metrics-exporter/releases/tag/v0.18.0 🙏

**Comment by metanull-operator** [comment]
I don't recall what version I was using at the time. I have since upgraded to newer versions. It sounds like this can be closed.
